/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eduplay;

import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ListModel;

/**
 *
 * @author cosme
 */
public class prograGame extends javax.swing.JFrame {
    DefaultListModel<String> model= new DefaultListModel<>();
    public int nivel =1;
    HiloPersonaje h;
    
    /**
     * Creates new form prograGame
     */
    public prograGame() {
        initComponents();
        this.remove(panelJuego);
        setNivel();
        Plataforma.prg=this;
        
    }

    public void setNivel() {
        listaMovimientos1.setModel (model);
        listaMovimientos2.setModel (model);
        listaMovimientos3.setModel (model);
        JPanel panel=null;
        this.remove(panelJuego);
        
        switch(nivel){
            case 1:
                panel=panelJuego1;
                jugador= jugador1;
                lblGanar1.setVisible(false);
                btnGanar1.setVisible(false);
                Plataforma.btnGanaste= btnGanar1;
                Plataforma.lblGanaste=lblGanar1;
                break;
            case 2:
                panel= panelJuego2;
                jugador=jugador3;
                
                lblGanar2.setVisible(false);
                btnGanar2.setVisible(false);
                Plataforma.btnGanaste= btnGanar2;
                Plataforma.lblGanaste=lblGanar2;
                break;
            case 3:
                panel= panelJuego3;
                jugador=jugador2;
                lblGanar3.setVisible(false);
                btnGanar3.setVisible(false);
                Plataforma.btnGanaste= btnGanar3;
                Plataforma.lblGanaste=lblGanar3;
                break;
        }
        
        panelJuego=panel;
        Plataforma.p= panelJuego;
        
        this.add(panelJuego);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego1 = new javax.swing.JPanel();
        lblGanar1 = new javax.swing.JLabel();
        btnGanar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMovimientos1 = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jugador1 = new javax.swing.JLabel();
        btnEjecutar1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblBackground1 = new javax.swing.JLabel();
        panelJuego3 = new javax.swing.JPanel();
        btnGanar3 = new javax.swing.JButton();
        lblGanar3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaMovimientos2 = new javax.swing.JList<>();
        jToggleButton2 = new javax.swing.JToggleButton();
        jugador2 = new javax.swing.JLabel();
        btnEjecutar2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lblBackground2 = new javax.swing.JLabel();
        panelJuego2 = new javax.swing.JPanel();
        lblGanar2 = new javax.swing.JLabel();
        btnGanar2 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaMovimientos3 = new javax.swing.JList<>();
        jugador3 = new javax.swing.JLabel();
        btnEjecutar3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        lblBackground3 = new javax.swing.JLabel();
        panelMovimientosDisponibles = new javax.swing.JPanel();
        btnReiniciar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBrincar = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        panelJuego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMovimientos = new javax.swing.JList<>();
        jugador = new javax.swing.JLabel();
        btnEjecutar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        panelJuego1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGanar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volando.png"))); // NOI18N
        lblGanar1.setToolTipText("");
        panelJuego1.add(lblGanar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, -1));

        btnGanar1.setText("Siguiente nivel");
        btnGanar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanar1ActionPerformed(evt);
            }
        });
        panelJuego1.add(btnGanar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        listaMovimientos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaMovimientos1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(listaMovimientos1);

        panelJuego1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 127, 183));

        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setEnabled(false);
        jToggleButton1.setFocusable(false);
        panelJuego1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 120, 160));

        jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caminando.png"))); // NOI18N
        panelJuego1.add(jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        btnEjecutar1.setText("Ejecutar");
        btnEjecutar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutar1ActionPerformed(evt);
            }
        });
        panelJuego1.add(btnEjecutar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setEnabled(false);
        jButton4.setFocusable(false);
        jButton4.setRequestFocusEnabled(false);
        jButton4.setRolloverEnabled(false);
        panelJuego1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 200, 90));

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setEnabled(false);
        jButton5.setFocusable(false);
        jButton5.setRequestFocusEnabled(false);
        jButton5.setRolloverEnabled(false);
        panelJuego1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 610, 100));

        lblBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel1.jpg"))); // NOI18N
        lblBackground1.setText("jLabel1");
        lblBackground1.setMinimumSize(new java.awt.Dimension(1366, 768));
        lblBackground1.setName(""); // NOI18N
        panelJuego1.add(lblBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 940, 770));

        panelJuego3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGanar3.setText("Siguiente nivel");
        btnGanar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanar3ActionPerformed(evt);
            }
        });
        panelJuego3.add(btnGanar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        lblGanar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volando.png"))); // NOI18N
        lblGanar3.setToolTipText("");
        panelJuego3.add(lblGanar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, -1));

        listaMovimientos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaMovimientos2KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(listaMovimientos2);

        panelJuego3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 127, 183));

        jToggleButton2.setBorderPainted(false);
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.setEnabled(false);
        jToggleButton2.setFocusable(false);
        panelJuego3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 130, 170));

        jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caminando.png"))); // NOI18N
        panelJuego3.add(jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 434, -1, -1));

        btnEjecutar2.setText("Ejecutar");
        btnEjecutar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutar2ActionPerformed(evt);
            }
        });
        panelJuego3.add(btnEjecutar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setEnabled(false);
        jButton7.setFocusable(false);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setRolloverEnabled(false);
        panelJuego3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 490, 100));

        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setEnabled(false);
        jButton9.setFocusable(false);
        jButton9.setRequestFocusEnabled(false);
        jButton9.setRolloverEnabled(false);
        panelJuego3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 130, 60));

        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setEnabled(false);
        jButton8.setFocusable(false);
        jButton8.setRequestFocusEnabled(false);
        jButton8.setRolloverEnabled(false);
        panelJuego3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 130, 60));

        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setEnabled(false);
        jButton10.setFocusable(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverEnabled(false);
        panelJuego3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 120, 60));

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setEnabled(false);
        jButton6.setFocusable(false);
        jButton6.setRequestFocusEnabled(false);
        jButton6.setRolloverEnabled(false);
        panelJuego3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 60, 60));

        lblBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel3.jpg"))); // NOI18N
        lblBackground2.setText("jLabel1");
        lblBackground2.setMinimumSize(new java.awt.Dimension(1366, 768));
        lblBackground2.setName(""); // NOI18N
        panelJuego3.add(lblBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 940, 770));

        panelJuego2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGanar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volando.png"))); // NOI18N
        lblGanar2.setToolTipText("");
        panelJuego2.add(lblGanar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, -1));

        btnGanar2.setText("Siguiente nivel");
        btnGanar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanar2ActionPerformed(evt);
            }
        });
        panelJuego2.add(btnGanar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jToggleButton3.setBorderPainted(false);
        jToggleButton3.setContentAreaFilled(false);
        jToggleButton3.setEnabled(false);
        jToggleButton3.setFocusable(false);
        panelJuego2.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 120, 160));

        listaMovimientos3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaMovimientos3KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(listaMovimientos3);

        panelJuego2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 127, 183));

        jugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caminando.png"))); // NOI18N
        panelJuego2.add(jugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 372, -1, -1));

        btnEjecutar3.setText("Ejecutar");
        btnEjecutar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutar3ActionPerformed(evt);
            }
        });
        panelJuego2.add(btnEjecutar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setEnabled(false);
        jButton11.setFocusable(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverEnabled(false);
        panelJuego2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 120, 60));

        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setEnabled(false);
        jButton12.setFocusable(false);
        jButton12.setRequestFocusEnabled(false);
        jButton12.setRolloverEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panelJuego2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 120, 50));

        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setEnabled(false);
        jButton13.setFocusable(false);
        jButton13.setRequestFocusEnabled(false);
        jButton13.setRolloverEnabled(false);
        panelJuego2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 70, 50));

        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setEnabled(false);
        jButton14.setFocusable(false);
        jButton14.setRequestFocusEnabled(false);
        jButton14.setRolloverEnabled(false);
        panelJuego2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 350, 100));

        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setEnabled(false);
        jButton15.setFocusable(false);
        jButton15.setRequestFocusEnabled(false);
        jButton15.setRolloverEnabled(false);
        panelJuego2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 120, 50));

        lblBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel2.jpg"))); // NOI18N
        lblBackground3.setText("jLabel1");
        lblBackground3.setMinimumSize(new java.awt.Dimension(1366, 768));
        lblBackground3.setName(""); // NOI18N
        panelJuego2.add(lblBackground3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 940, 770));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMovimientosDisponibles.setBackground(new java.awt.Color(102, 255, 255));
        panelMovimientosDisponibles.setPreferredSize(new java.awt.Dimension(150, 48));
        panelMovimientosDisponibles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setBorderPainted(false);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        panelMovimientosDisponibles.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 150, 50));
        btnReiniciar.setVisible(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelMovimientosDisponibles.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 70));

        btnBrincar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brincar.png"))); // NOI18N
        btnBrincar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrincarActionPerformed(evt);
            }
        });
        panelMovimientosDisponibles.add(btnBrincar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 70));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adelante.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panelMovimientosDisponibles.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 70));

        getContentPane().add(panelMovimientosDisponibles, java.awt.BorderLayout.EAST);

        panelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volando.png"))); // NOI18N
        jLabel1.setToolTipText("");
        panelJuego.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 120, -1));

        jButton16.setText("Siguiente nivel");
        panelJuego.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        listaMovimientos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaMovimientosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listaMovimientos);

        panelJuego.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 127, 183));

        jugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caminando.png"))); // NOI18N
        panelJuego.add(jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        panelJuego.add(btnEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setEnabled(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.setRolloverEnabled(false);
        panelJuego.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 200, 90));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        panelJuego.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 610, 100));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel1.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        lblBackground.setMinimumSize(new java.awt.Dimension(1366, 768));
        lblBackground.setName(""); // NOI18N
        panelJuego.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 940, 770));

        getContentPane().add(panelJuego, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        crearHilo();
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void listaMovimientosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaMovimientosKeyPressed
           if(evt.getKeyCode()==KeyEvent.VK_DELETE){
               int index=listaMovimientos.getSelectedIndex();
               if(index>=0)
                    model.remove(index);
           }
    }//GEN-LAST:event_listaMovimientosKeyPressed

    private void btnEjecutar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutar1ActionPerformed
        crearHilo();;
    }//GEN-LAST:event_btnEjecutar1ActionPerformed

    private void btnEjecutar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutar2ActionPerformed
        crearHilo();
    }//GEN-LAST:event_btnEjecutar2ActionPerformed

    private void listaMovimientos1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaMovimientos1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DELETE){
               int index=listaMovimientos1.getSelectedIndex();
               if(index>=0){
                    model.remove(index);
                    listaMovimientos1.setSelectedIndex(index);
               }
           }
    }//GEN-LAST:event_listaMovimientos1KeyPressed

    private void listaMovimientos2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaMovimientos2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DELETE){
               int index=listaMovimientos2.getSelectedIndex();
               if(index>=0){
                    model.remove(index);
                    listaMovimientos2.setSelectedIndex(index);
               }
           }
    }//GEN-LAST:event_listaMovimientos2KeyPressed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnEjecutar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutar3ActionPerformed
       
        crearHilo();
       
    }//GEN-LAST:event_btnEjecutar3ActionPerformed

    public void crearHilo() {
        h= new HiloPersonaje(model, jugador,btnReiniciar);
        h.start();
    }

    private void listaMovimientos3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaMovimientos3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DELETE){
            int index=listaMovimientos3.getSelectedIndex();
            if(index>=0){
                model.remove(index);
                listaMovimientos3.setSelectedIndex(index);
            }
        }
    }//GEN-LAST:event_listaMovimientos3KeyPressed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
//        this.dispose();
//        new prograGame().setVisible(true);
        try{
            btnReiniciar.setVisible(false);
            
            h.interrupt();
        }catch(Exception e){
            System.out.println("Error esperado "+e.getMessage());
        }
          model=new DefaultListModel<>();
          invalidate();
          revalidate();
          setNivel();
          repaint();
                
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnBrincarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrincarActionPerformed
        model.addElement("Brincar");
    }//GEN-LAST:event_btnBrincarActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       model.addElement("Adelante");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        model.addElement("Subir");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGanar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanar1ActionPerformed

        //btnReiniciar.doClick();
    }//GEN-LAST:event_btnGanar1ActionPerformed

    private void btnGanar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanar2ActionPerformed
      
        //btnReiniciar.doClick();
    }//GEN-LAST:event_btnGanar2ActionPerformed

    private void btnGanar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanar3ActionPerformed
     
        //btnReiniciar.doClick();
    }//GEN-LAST:event_btnGanar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prograGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prograGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prograGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prograGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prograGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrincar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnEjecutar1;
    private javax.swing.JButton btnEjecutar2;
    private javax.swing.JButton btnEjecutar3;
    private javax.swing.JButton btnGanar1;
    private javax.swing.JButton btnGanar2;
    private javax.swing.JButton btnGanar3;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel jugador;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador2;
    private javax.swing.JLabel jugador3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackground1;
    private javax.swing.JLabel lblBackground2;
    private javax.swing.JLabel lblBackground3;
    private javax.swing.JLabel lblGanar1;
    private javax.swing.JLabel lblGanar2;
    private javax.swing.JLabel lblGanar3;
    private javax.swing.JList<String> listaMovimientos;
    private javax.swing.JList<String> listaMovimientos1;
    private javax.swing.JList<String> listaMovimientos2;
    private javax.swing.JList<String> listaMovimientos3;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelJuego1;
    private javax.swing.JPanel panelJuego2;
    private javax.swing.JPanel panelJuego3;
    private javax.swing.JPanel panelMovimientosDisponibles;
    // End of variables declaration//GEN-END:variables
}
